metrics:
  stock:
    url: 
      - "https://www.stockwatch.com/Quote/Detail?U:RIVN"
      - "https://www.stockwatch.com/Quote/Detail?U:TSLA"
    type: gauge
    description: "Exports the current coin value based on the web scrape"
